version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql:8.1.0
    volumes:
      - ./scripts:/home
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'

networks:
  default:
    driver: bridge
